### ISSUE TITLE
Fix credential issue

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/fullstop#26]
Fix credential issue after deployment

**Comment by jbellmann** [comment]
Do we have an stacktrace, exception or some other output?

**Comment by Gregsen** [comment]
```java
2015-04-13 13:57:07.210 ERROR 12 --- [pool-1-thread-1] .a.s.c.p.AWSCloudTrailProcessingExecutor : Executor failed to process a task. Unable to load AWS credentials from any provider in the chain

com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2282)
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1021)
	at com.amazonaws.services.cloudtrail.processinglibrary.manager.SqsManager.pollQueue(SqsManager.java:126)
	at com.amazonaws.services.cloudtrail.processinglibrary.reader.EventReader.getSources(EventReader.java:114)
	at com.amazonaws.services.cloudtrail.processinglibrary.AWSCloudTrailProcessingExecutor$ScheduledJob.run(AWSCloudTrailProcessingExecutor.java:172)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Gregsen** [comment]
Not a problem in the code. IAM Role has been fixed.
