### ISSUE TITLE
Installation requrments version conflict

### ISSUE THREAD

**Issue by a-baturin** [zalando-stups/fullstop#409]
Command `pip3 install --upgrade stups-fullstop` does not work on Ubuntu 16.04
Gives 
```
Collecting stups-fullstop (from stups)
  Using cached stups-fullstop-1.0.24.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    flake8.__pycache__.reporter.cpython-35: module references __file__
    flake8.tests.__pycache__.test_integration.cpython-35: module references __file__
    flake8.tests.__pycache__._test_warnings.cpython-35: module references __file__
    
    Installed /tmp/pip-build-qj1lvi6n/stups-fullstop/.eggs/flake8-2.5.4-py3.5.egg
    Searching for mccabe<0.5,>=0.2.1
    Reading https://pypi.python.org/simple/mccabe/
    Best match: mccabe 0.4.0
    Downloading https://pypi.python.org/packages/f6/e7/54461a958bb8b16f8db5f849d5d08b7d74153e064ac385fb68ff09f0bd27/mccabe-0.4.0.tar.gz#md5=8c425db05f310adcd4bb174b991f26f5
    Processing mccabe-0.4.0.tar.gz
    Writing /tmp/easy_install-8e6mh_0e/mccabe-0.4.0/setup.cfg
    Running mccabe-0.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8e6mh_0e/mccabe-0.4.0/egg-dist-tmp-gi7031xp
    
    Installed /tmp/easy_install-8e6mh_0e/mccabe-0.4.0/temp/easy_install-zg990i_j/pytest-runner-2.7.1/.eggs/setuptools_scm-1.11.0-py3.5.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/easy_install-8e6mh_0e/mccabe-0.4.0/.eggs/pytest_runner-2.7.1-py3.5.egg
    creating /tmp/pip-build-qj1lvi6n/stups-fullstop/.eggs/mccabe-0.4.0-py3.5.egg
    Extracting mccabe-0.4.0-py3.5.egg to /tmp/pip-build-qj1lvi6n/stups-fullstop/.eggs
    
    Installed /tmp/pip-build-qj1lvi6n/stups-fullstop/.eggs/mccabe-0.4.0-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qj1lvi6n/stups-fullstop/setup.py", line 140, in <module>
        setup_package()
      File "/tmp/pip-build-qj1lvi6n/stups-fullstop/setup.py", line 135, in setup_package
        entry_points={'console_scripts': CONSOLE_SCRIPTS},
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1085, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 695, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (pyflakes 1.1.0 (/usr/lib/python3/dist-packages), Requirement.parse('pyflakes<1.1,>=0.8.1'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qj1lvi6n/stups-fullstop/

```
Command `pip3 install stups-fullstop==1.0.8` works fine.

**Comment by mrandi** [comment]
@a-baturin please report here https://github.com/zalando-stups/fullstop-cli  your issue. This repo is only for the backend.
