### ISSUE TITLE
ClassCastException in fullstop-jobs

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/fullstop#431]
### Expected behavior

This one should probably not occur:

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
at org.zalando.stups.fullstop.jobs.elb.FetchElasticLoadBalancersJob.lambda$writeViolation$47(FetchElasticLoadBalancersJob.java:286) ~[fullstop-jobs-1.2.0-SNAPSHOT.jar!/:?]
at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_66-internal]
at org.zalando.stups.fullstop.jobs.elb.FetchElasticLoadBalancersJob.writeViolation(FetchElasticLoadBalancersJob.java:286) ~[fullstop-jobs-1.2.0-SNAPSHOT.jar!/:?]
at org.zalando.stups.fullstop.jobs.elb.FetchElasticLoadBalancersJob.run(FetchElasticLoadBalancersJob.java:217) ~[fullstop-jobs-1.2.0-SNAPSHOT.jar!/:?]
at sun.reflect.GeneratedMethodAccessor232.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_66-internal]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_66-internal]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_66-internal]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66-internal]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66-internal]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
```

**Comment by harti2006** [comment]
fixed by #454
